insert into public.profiles (id, username, display_name, bio, profile_color, favorite_genres)
values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'luca', 'Luca', 'Peak Music Reviews. Rating music so you do not have to.', '#1e90ff', array['R&B', 'Hip-Hop', 'Pop', 'Alternative'])
on conflict (id) do update set display_name = 'Luca', bio = 'Peak Music Reviews. Rating music so you do not have to.', profile_color = '#1e90ff', favorite_genres = array['R&B', 'Hip-Hop', 'Pop', 'Alternative'];

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, review_date, summary, snippet, cover_image, standout_tracks) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'house-of-balloons-the-weeknd', 'House Of Balloons', 'The Weeknd', 10.0, 'R&B', 'mixtape', '2011-03-21', '2026-03-01', 'As my first 10/10 rating I have what I say is the "Greatest Album of All Time" which is the debut mixtape/album by The Weeknd, who I also think is the greatest artist of all time. I have never heard an album before that has put me in such a vivid experience that I can see and feel, more than this mixtape. House Of Balloons is a life-changing album that is so dark and eerie, that makes you want to open a window and breath as you are surrounded by girls, drinks, and drugs all around you in the most drug-induced experience ever. With this explanation I am referring to my favorite track of this mixtape as well as my favorite song of all time, "House Of Balloons / Glass Table Girls". I truly do not believe any song on this album is bad, even the bonus song "Twenty Eight" being great as well. To round out my top 3 songs however I would say "The Knowing" and "Wicked Games" are truly fantastic songs and overall this album would be my personal recommendation for anyone in music to give a listen and see if they agree with this 10/10 review of mine.', 'The "Greatest Album of All Time" -- a life-changing, dark, and eerie experience. The first and only 10/10.', '/reviews/house-of-balloons-the-weeknd.png', '[{"title":"House Of Balloons / Glass Table Girls","spotifyUrl":"https://open.spotify.com/track/2r7BPog74oaTG5shNYiUnV"},{"title":"The Knowing","spotifyUrl":"https://open.spotify.com/track/6tjsbysvZh8Pq8DZA5ldrn"},{"title":"Wicked Games","spotifyUrl":"https://open.spotify.com/track/00aqkszH1FdUiJJWvX6iEl"}]'::jsonb) on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, review_date, summary, snippet, cover_image, standout_tracks) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'the-romantic-bruno-mars', 'The Romantic', 'Bruno Mars', 8.1, 'Pop', 'album', '2026-02-27', '2026-03-01', 'After nearly 10 years, Bruno Mars comes back with a short solo album, with many Latin influences. The album sounds familiar as the formula many have learned to fall in love with over the years continues to win over hearts, especially with standout tracks such as "Risk It All", "Why You Wanna Fight?", and "On My Soul" being my personal favorites. This fantastic album was all killer no filler but personally after such a long wait I wish we could have had a bit more, although Bruno Mars is not known for lengthy solo albums, for the wait it would have been a nice touch. The production and story of the album is great with a few low-lights in my opinion such as "God Was Showing Off", and "Something Serious", dropping my rating slightly but still putting this album in elite territory for 2026 releases, going with a strong 8.1/10.', 'After nearly 10 years, Bruno Mars comes back with a short solo album. All killer no filler -- elite territory for 2026.', '/reviews/the-romantic-bruno-mars.png', '[{"title":"Risk It All","spotifyUrl":"https://open.spotify.com/track/5y2ijHECwFYWqcAHKTZgzD"},{"title":"Why You Wanna Fight?","spotifyUrl":"https://open.spotify.com/track/3Ac4AjYkqsvop2ydbSAhTX"},{"title":"On My Soul","spotifyUrl":"https://open.spotify.com/track/4i4BVY2JiH4mDSLIBdNGKD"}]'::jsonb) on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'channel-orange-frank-ocean', 'Channel Orange', 'Frank Ocean', 9.8, 'R&B', 'album', '2012-07-10', '9.8/10 -- Full review coming soon.', '/reviews/channel-orange-frank-ocean.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'thursday-the-weeknd', 'Thursday', 'The Weeknd', 9.7, 'R&B', 'mixtape', '2011-08-18', '9.7/10 -- Full review coming soon.', '/reviews/thursday-the-weeknd.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'fever-buckshot-fakemink', 'Fever', 'Buckshot & fakemink', 9.5, 'Hip-Hop', 'single', '2025-08-22', '9.5/10 -- Full review coming soon.', '/reviews/fever-buckshot-fakemink.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'blonde-frank-ocean', 'Blonde', 'Frank Ocean', 9.4, 'R&B', 'album', '2016-08-20', '9.4/10 -- Full review coming soon.', '/reviews/blonde-frank-ocean.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'echoes-of-silence-the-weeknd', 'Echoes of Silence', 'The Weeknd', 9.2, 'R&B', 'mixtape', '2011-12-21', '9.2/10 -- Full review coming soon.', '/reviews/echoes-of-silence-the-weeknd.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'after-hours-the-weeknd', 'After Hours', 'The Weeknd', 9.0, 'R&B', 'album', '2020-03-20', '9.0/10 -- Full review coming soon.', '/reviews/after-hours-the-weeknd.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'in-rainbows-radiohead', 'In Rainbows', 'Radiohead', 9.0, 'Alternative', 'album', '2007-10-10', '9.0/10 -- Full review coming soon.', '/reviews/in-rainbows-radiohead.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'playboi-carti-playboi-carti', 'Playboi Carti', 'Playboi Carti', 8.8, 'Hip-Hop', 'mixtape', '2017-04-14', '8.8/10 -- Full review coming soon.', '/reviews/playboi-carti-playboi-carti.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'get-up-newjeans', 'Get Up', 'NewJeans', 8.8, 'Pop', 'EP', '2023-07-21', '8.8/10 -- Full review coming soon.', '/reviews/get-up-newjeans.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'rodeo-travis-scott', 'Rodeo', 'Travis Scott', 8.7, 'Hip-Hop', 'album', '2015-09-04', '8.7/10 -- Full review coming soon.', '/reviews/rodeo-travis-scott.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'who-really-cares-tv-girl', 'Who Really Cares', 'TV Girl', 8.7, 'Alternative', 'album', '2016-03-04', '8.7/10 -- Full review coming soon.', '/reviews/who-really-cares-tv-girl.png') on conflict (user_id, slug) do nothing;

insert into public.reviews (user_id, slug, title, artist, rating, genre, release_type, release_date, snippet, cover_image) values ('8587299c-dbb8-49a9-b984-e25c089a65fc', 'die-lit-playboi-carti', 'Die Lit', 'Playboi Carti', 8.3, 'Hip-Hop', 'album', '2018-05-11', '8.3/10 -- Full review coming soon.', '/reviews/die-lit-playboi-carti.png') on conflict (user_id, slug) do nothing;
